// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDac6-KZpDP4HvzHhsi5lsTuVMbO3hS0l0',
    appId: '1:960911048649:android:2895198e917bf532cc7218',
    messagingSenderId: '960911048649',
    projectId: 'flutter-e-commerce-a4ba0',
    storageBucket: 'flutter-e-commerce-a4ba0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnIucwX5Z9YmRZcoJhe8DGvFpmbSZO6Vw',
    appId: '1:960911048649:ios:5278a4a34802d2b0cc7218',
    messagingSenderId: '960911048649',
    projectId: 'flutter-e-commerce-a4ba0',
    storageBucket: 'flutter-e-commerce-a4ba0.appspot.com',
    androidClientId: '960911048649-07aljqh1qmcc9rlo1hsqhan2nt29l2pb.apps.googleusercontent.com',
    iosClientId: '960911048649-1bp3d8f1ve0mi0s0v12p9js37h9enreb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterEcommerce',
  );
}
